[project]
name = "foresite-handbook"
version = "0.1.0"
description = "ForeSITE Group Handbook"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mkdocs>=1.5.0",
    "mkdocs-material>=9.0.0",
]

[dependency-groups]
dev = []