#!/usr/bin/env Rscript

# Minimal test script to verify workflow setup
cat("Project Status Update Test\n")
cat("==========================\n")

# Basic file system check
if (file.exists("data")) {
  yaml_files <- list.files("data", pattern = "ya?ml$")
  cat(paste("Found", length(yaml_files), "YAML files in data directory\n"))
  
  # Show first few files
  if (length(yaml_files) > 0) {
    cat("First 5 YAML files:\n")
    for (i in 1:min(5, length(yaml_files))) {
      cat(paste(" -", yaml_files[i], "\n"))
    }
  }
} else {
  cat("ERROR: data directory not found\n")
  quit(status = 1)
}

# Create a placeholder project_status.md
content <- c(
  "# Project Status Dashboard",
  "",
  paste("Last updated:", Sys.time(), "(UTC)"),
  "",
  "This is a test run of the project status workflow.",
  "",
  "The system found", length(yaml_files), "YAML files in the data directory.",
  "",
  "Full functionality will be available once all dependencies are properly configured.",
  "",
  "---",
  "",
  "*This report is automatically generated by the [project status workflow](https://github.com/EpiForeSITE/software/actions).*"
)

writeLines(content, "project_status.md")
cat("Generated project_status.md successfully!\n")
cat("Workflow test completed.\n")