name: Build README

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-commit:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.4.1

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      # - name: Setup R
      #   uses: r-lib/actions/setup-r@v2
      
      - name: Install R dependencies
        run: Rscript -e "install.packages('writexl')"
      
      - name: Render README with Quarto
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: README.qmd
      # - name: Render README with Quarto
      #   run: quarto render README.qmd

      # Commit all changed files back to the repository
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automatic README update
          
